name: CI

on:
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  notify_about_prs_after_noon:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write  # Grant permission to comment on PRs
      contents: read        # Allow read access to the repo content
    steps:
      - name: Set Current env.DAY (Mon, Tue, ...) and env.HOUR (0..23) in Eastern Timezone
        shell: bash
        run: echo "DAY=$(TZ=":America/New_York" date +'%a')" >> $GITHUB_ENV && echo "HOUR=$(TZ=":America/New_York" date +'%H')" >> $GITHUB_ENV

      - name: Checkout PR
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Find First File In Commit
        id: get_first_file
        run: |
          # Check if there are any files in the commit
          FIRST_FILE=$(git diff --name-only HEAD^ HEAD | head -n 1)
          
          if [ -z "$FIRST_FILE" ]; then
            echo "No files found in the latest commit."
            echo "first_file=" >> $GITHUB_ENV
          else
            echo "First file: $FIRST_FILE"
            echo "first_file=$FIRST_FILE" >> $GITHUB_ENV
          fi

      - name: Add Review Comment During Freeze Hours
        if: env.first_file != '' && env.HOUR >= 12
        run: |
          FILE_NAME="${{ env.first_file }}"
          COMMIT_ID="${{ github.event.pull_request.head.sha }}"
          PR_NUMBER="${{ github.event.pull_request.number }}"
          COMMENT='**⚠ After Hours PR**\n\nPlease review this @NickHirras'

          curl -s -X POST "${GITHUB_API_URL}/repos/${{ github.repository }}/pulls/${PR_NUMBER}/comments" \
          -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          -H "Accept: application/vnd.github.v3+json" \
          -d "{\"body\": \"${COMMENT}\", \"path\": \"${FILE_NAME}\", \"commit_id\": \"${COMMIT_ID}\", \"subject_type\": \"file\"}"
      